#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 10
#define RGBLIGHT_SLEEP
#define RGB_DISABLE_TIMEOUT 900000 // milliseconds
#define RGB_DISABLE_WHEN_USB_SUSPENDED 1

#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 100